"""Canonical Pydantic models for Screened."""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field, field_validator
import uuid

from backend.models.base import *
from backend.models.investigation import *
from backend.models.deep_vetting import *
from backend.models.dossier import *

class DeepVettingDimension(BaseModel):
    id: str = Field(default_factory=generate_uuid)
    dimensionKey: str  # e.g., "CORPORATE_REGISTRY", "DOMAIN_PROVENANCE", "BOILERPLATE_PLAGIARISM", "PERSONNEL_DOSSIER", "VENUE_CORROBORATION", "ALUMNI_FOOTPRINT", "IMAGE_PROVENANCE"
    title: str
    category: QuestionCategory
    status: VettingSignalStatus
    confidenceScore: int = Field(default=85, ge=0, le=100)
    summary: str
    signalsFound: List[str] = Field(default_factory=list)
    corroboratingSources: List[str] = Field(default_factory=list)
    riskWeight: str = "MEDIUM"  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    imageArtifacts: Optional[List[ImageForensicRecord]] = None

class KeyPerson(BaseModel):
    name: str
    roles: List[str] = Field(default_factory=list)
    role: Optional[str] = None
    appointmentDate: Optional[str] = None
    companies: Optional[List[str]] = None
    otherDirectorships: Optional[List[str]] = None
    associatedFestivals: Optional[List[str]] = None
    flags: Optional[List[str]] = None
    isFestivalMillSuspect: Optional[bool] = False
    hasDistributionOverlap: Optional[bool] = False
    notes: Optional[str] = None
    avatarUrl: Optional[str] = None
    linkedinUrl: Optional[str] = None
    companiesHouseUrl: Optional[str] = None
    facebookUrl: Optional[str] = None
    websiteUrl: Optional[str] = None
    imdbUrl: Optional[str] = None
    wikipediaUrl: Optional[str] = None
    twitterUrl: Optional[str] = None

class DeepVettingReport(BaseModel):
    festivalName: str
    overallAuthenticityScore: int = Field(default=80, ge=0, le=100)
    totalFlags: int = 0
    dimensions: List[DeepVettingDimension] = Field(default_factory=list)
    keyPersonnel: Optional[List[KeyPerson]] = None
    imageArtifacts: Optional[List[ImageForensicRecord]] = None
    disclaimer: Optional[str] = "This analysis is generated by an automated AI tool and may contain inaccuracies or false positives. All findings regarding individuals, corporate directorships, and potential conflicts of interest must be manually reviewed and corroborated before taking action."
    generatedAt: str = Field(default_factory=get_current_iso)
    degraded: Optional[bool] = False

class PremiereRiskLevel(str, Enum):
    LOW_RISK = "LOW_RISK"
    MODERATE_RISK = "MODERATE_RISK"
    HIGH_BURN_RISK = "HIGH_BURN_RISK"

class PremiereRiskAssessment(BaseModel):
    riskScore: int = Field(default=50, ge=0, le=100)
    riskLevel: PremiereRiskLevel = PremiereRiskLevel.MODERATE_RISK
    premiereDemand: str = "No Premiere Requirement"
    accreditationStatus: str = "Unaccredited"
    buyerPressFootprint: str = "Limited trade and buyer presence"
    verdictRationale: str = ""
    recommendation: str = ""

class FeeTier(BaseModel):
    tierName: str
    amount: float
    currency: str = "£"
    deadlineDate: Optional[str] = None
    surgePercentage: int = 0

class FeeEscalationModel(BaseModel):
    currency: str = "£"
    tiers: List[FeeTier] = Field(default_factory=list)
    spikeAlert: Optional[str] = None
    averageMarketFee: Optional[str] = None
    percentile: Optional[int] = None

class ForensicTrioItem(BaseModel):
    status: VettingSignalStatus = VettingSignalStatus.INFORMATIONAL
    headline: str
    summary: str
    educationalContext: Optional[str] = None
    signals: List[str] = Field(default_factory=list)
    relatedEntities: Optional[List[str]] = None

class ForensicIntelligenceSummary(BaseModel):
    scamPattern: ForensicTrioItem
    juryConflict: ForensicTrioItem
    venueReality: ForensicTrioItem

class TestPipelineRequest(BaseModel):
    festivalName: str
    optionalUrl: Optional[str] = None
    additionalContext: Optional[str] = None
    intent: str = "Vet before submitting"

class TestPipelineResponse(BaseModel):
    festivalName: str
    sourcesFound: int
    sources: List[SourceRecord]
    extractedClaims: List[AtomicClaim]
    deepVetting: Optional[DeepVettingReport] = None
    summaryNarrative: str
    durationSeconds: float

